version: '3.8'
services:
  gateway:
    restart: always
    build:
      dockerfile: gateway/Dockerfile.prod
      context: .
    depends_on:
      - items_service
  items_service:
    restart: always
    build:
      dockerfile: microservices/items_service/Dockerfile.prod
      context: .
      target: api_server
  nginx:
    restart: always
    build:
      dockerfile: nginx/Dockerfile.prod
      context: .
    depends_on:
      - gateway
    ports:
      - "3050:80"