version: '3.8'
services:
  gateway:
    restart: always
    build:
      dockerfile: gateway/Dockerfile.prod
      context: .
    depends_on:
      - backend
  backend:
    restart: always
    build:
      dockerfile: apps/backend/Dockerfile.prod
      context: .
  nginx:
    restart: always
    build:
      dockerfile: nginx/Dockerfile.prod
      context: .
    depends_on:
      - gateway
    ports:
      - "3050:80"