version: '3.8'
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  gateway_dev:
    restart: always
    build:
      dockerfile: gateway/Dockerfile
      context: .
    volumes:
      - ./gateway/config.json:/app/config.json
  nginx_dev:
    restart: always
    build:
      dockerfile: nginx/Dockerfile
      context: .
    depends_on:
      - gateway_dev
    ports:
      - "3051:80"
volumes:
  database-data: