version: '3.8'
services:
  gateway_dev:
    restart: always
    build:
      dockerfile: gateway/Dockerfile
      context: .
  nginx_dev:
    restart: always
    build:
      dockerfile: nginx/Dockerfile
      context: .
    depends_on:
      - gateway_dev
    ports:
      - "3050:80"