FROM node:16-alpine as build
RUN apk add git
WORKDIR /app
COPY . .
RUN npm i --only-production
RUN npm run build:frontend
# production environment
FROM nginx:stable-alpine
COPY --from=build /app/apps/frontend/build /usr/share/nginx/html
COPY --from=build /app/nginx/production.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]