/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { PickFindingPropsRuleIdOrTypeOrMetadataOrLocation } from './pickFindingPropsRuleIdOrTypeOrMetadataOrLocation';

export type FindingCreationParams = PickFindingPropsRuleIdOrTypeOrMetadataOrLocation;
