/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { MetadataProps } from './metadataProps';
import type { LocationProps } from './locationProps';

export interface FindingProps {
  metadata: MetadataProps;
  location: LocationProps;
  ruleId: string;
  type: string;
  itemId: string;
  id: string;
}
