/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { Finding } from './finding';
import type { ItemStatus } from './itemStatus';

export interface ItemProps {
  finishedAt?: string;
  scanningAt?: string;
  queuedAt: string;
  findings: Finding[];
  repositoryName: string;
  status: ItemStatus;
  id: string;
}
