/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { FindingCreationParams } from './findingCreationParams';

export type ItemCreationParamsAllOf = {
  findings?: FindingCreationParams[];
};
