/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */

export type ItemStatus = typeof ItemStatus[keyof typeof ItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemStatus = {
  Queued: 'Queued',
} as const;
