/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { LocationPropsPositions } from './locationPropsPositions';

export interface LocationProps {
  positions: LocationPropsPositions;
  path: string;
}
