/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { PickItemPropsExcludeKeyofItemPropsIdOrFindings } from './pickItemPropsExcludeKeyofItemPropsIdOrFindings';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitItemPropsIdOrFindings = PickItemPropsExcludeKeyofItemPropsIdOrFindings;
