/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { OmitItemPropsIdOrFindings } from './omitItemPropsIdOrFindings';
import type { PartialPickItemPropsIdOrFindings } from './partialPickItemPropsIdOrFindings';

export type PartialByItemPropsIdOrFindings = OmitItemPropsIdOrFindings & PartialPickItemPropsIdOrFindings;
