/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Make all properties in T optional
 */
export interface PartialPickFindingPropsId { [key: string]: any }
