/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { MetadataProps } from './metadataProps';
import type { LocationProps } from './locationProps';

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickFindingPropsRuleIdOrTypeOrMetadataOrLocation {
  ruleId: string;
  type: string;
  metadata: MetadataProps;
  location: LocationProps;
}
