/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */
import type { ItemStatus } from './itemStatus';
import type { FindingProps } from './findingProps';

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickItemPropsRepositoryNameOrStatusOrQueuedAtOrScanningAtOrFinishedAtOrFindings {
  repositoryName: string;
  status: ItemStatus;
  queuedAt: string;
  scanningAt?: string;
  finishedAt?: string;
  findings: FindingProps[];
}
