/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * items-service
 * OpenAPI spec version: 1.0.0
 */

export type Severity = typeof Severity[keyof typeof Severity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Severity = {
  HIGH: 'HIGH',
} as const;
